# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from load_model import crop_pred

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(753, 237)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.features_box = QtWidgets.QGroupBox(self.centralwidget)
        self.features_box.setGeometry(QtCore.QRect(0, 0, 751, 211))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)

        self.features_box.setFont(font)
        self.features_box.setMouseTracking(False)
        self.features_box.setObjectName("features_box")
        self.Submit = QtWidgets.QPushButton(self.features_box)
        self.Submit.setGeometry(QtCore.QRect(620, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)

        self.Submit.setFont(font)
        self.Submit.setObjectName("Submit")
        self.N_label = QtWidgets.QLabel(self.features_box)
        self.N_label.setGeometry(QtCore.QRect(110, 20, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)

        self.N_label.setFont(font)
        self.N_label.setObjectName("N_label")
        self.P_label = QtWidgets.QLabel(self.features_box)
        self.P_label.setGeometry(QtCore.QRect(290, 20, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)

        self.P_label.setFont(font)
        self.P_label.setObjectName("P_label")
        self.K_label = QtWidgets.QLabel(self.features_box)
        self.K_label.setGeometry(QtCore.QRect(490, 20, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)

        self.K_label.setFont(font)
        self.K_label.setObjectName("K_label")
        self.Temperature_label = QtWidgets.QLabel(self.features_box)
        self.Temperature_label.setGeometry(QtCore.QRect(620, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)

        self.Temperature_label.setFont(font)
        self.Temperature_label.setObjectName("Temperature_label")
        self.Rainfall_label = QtWidgets.QLabel(self.features_box)
        self.Rainfall_label.setGeometry(QtCore.QRect(460, 130, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)

        self.Rainfall_label.setFont(font)
        self.Rainfall_label.setObjectName("Rainfall_label")
        self.Ph_label = QtWidgets.QLabel(self.features_box)
        self.Ph_label.setGeometry(QtCore.QRect(280, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)

        self.Ph_label.setFont(font)
        self.Ph_label.setObjectName("Ph_label")
        self.Huminity_label = QtWidgets.QLabel(self.features_box)
        self.Huminity_label.setGeometry(QtCore.QRect(70, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)

        self.Huminity_label.setFont(font)
        self.Huminity_label.setObjectName("Huminity_label")
        self.N_in = QtWidgets.QTextEdit(self.features_box)
        self.N_in.setGeometry(QtCore.QRect(60, 60, 111, 31))
        self.N_in.setObjectName("N_in")
        self.P_in = QtWidgets.QTextEdit(self.features_box)
        self.P_in.setGeometry(QtCore.QRect(240, 60, 111, 31))
        self.P_in.setObjectName("P_in")
        self.K_in = QtWidgets.QTextEdit(self.features_box)
        self.K_in.setGeometry(QtCore.QRect(440, 60, 111, 31))
        self.K_in.setObjectName("K_in")
        self.Temperature_in = QtWidgets.QTextEdit(self.features_box)
        self.Temperature_in.setGeometry(QtCore.QRect(620, 60, 111, 31))
        self.Temperature_in.setObjectName("Temperature_in")
        self.Huminity_in = QtWidgets.QTextEdit(self.features_box)
        self.Huminity_in.setGeometry(QtCore.QRect(60, 160, 111, 31))
        self.Huminity_in.setObjectName("Huminity_in")
        self.Ph_in = QtWidgets.QTextEdit(self.features_box)
        self.Ph_in.setGeometry(QtCore.QRect(240, 160, 111, 31))
        self.Ph_in.setObjectName("Ph_in")
        self.Rainfall_in = QtWidgets.QTextEdit(self.features_box)
        self.Rainfall_in.setGeometry(QtCore.QRect(440, 160, 111, 31))
        self.Rainfall_in.setObjectName("Rainfall_in")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Submit.clicked.connect(self.recommend_crop)

    def recommend_crop(self):
        N = self.N_in
        P = self.P_in
        K = self.K_in
        T = self.Temperature_in
        H = self.Huminity_in
        ph = self.Ph_in
        R = self.Rainfall_in
        feature_names = [N, P, K, T, H, ph, R]
        feature_vals = []
        for i in feature_names:
            if i.toPlainText() == '':
                QMessageBox = QtWidgets.QMessageBox()
                QMessageBox.warning(None,"Warning","Please input all the required information!",QMessageBox.Ok,QMessageBox.No)
                break
        else: 
            try:
                for i in feature_names:
                    feature_vals.append(float(i.toPlainText()))
                N, P, K, T, H, ph, R = feature_vals
                crop_rcm = crop_pred(N, P, K, T, H, ph, R)
                
                cropBox = QtWidgets.QMessageBox()
                cropBox.setWindowTitle('Crop Recommendation')
                cropBox.setText(crop_rcm.upper())
                cropBox.exec_()
            except:
                QMessageBox = QtWidgets.QMessageBox()
                QMessageBox.warning(None,"Warning","Please ensure all inputs are numbers.",QMessageBox.Ok)
                for i in feature_names:
                    i.clear()
                    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.features_box.setTitle(_translate("MainWindow", "Crop Recommendation System"))
        self.Submit.setText(_translate("MainWindow", "Submit"))
        self.N_label.setText(_translate("MainWindow", "N"))
        self.P_label.setText(_translate("MainWindow", "P"))
        self.K_label.setText(_translate("MainWindow", "K"))
        self.Temperature_label.setText(_translate("MainWindow", "Temperature"))
        self.Rainfall_label.setText(_translate("MainWindow", "Rainfall"))
        self.Ph_label.setText(_translate("MainWindow", "Ph"))
        self.Huminity_label.setText(_translate("MainWindow", "Huminity"))
        self.N_in.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        
        self.P_in.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        
        self.K_in.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        
        self.Temperature_in.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        
        self.Huminity_in.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        
        self.Ph_in.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        
        self.Rainfall_in.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
